### PR TITLE
Finding tockmaster

### PR DESCRIPTION
**Pull request by brghena**
Updating to Tock master. It's been 24 days...

- [X] Updated FM25CL
- [x] Testing FM25CL
- [X] Fix error codes
- [X] Update timers
- [x] Update MCP and PCA drivers
- [ ] Add root level `make format` to run on apps and kernel

### CODE REVIEW

**Comment by adkinsjd** [comment]
@brghena I don't think we should be using tock specific error codes in signpost_api since it is generic. I think that was a reason that they were changed away from the tock specific error codes in the first place.

**Comment by brghena** [comment]
I'm confused. They already were Tock error codes. Unless you have EINVAL, EBUSY, SUCCESS, and FAIL defined elsewhere too...

**Comment by adkinsjd** [comment]
Okay you are right I thought Neal had redefined them. We should move away from the Tock error codes in portable signpost code, but I don't think it matters if it's in this PR.

**Comment by adkinsjd** [comment]
I'm pretty sure all my changes are working, but it's hard to do end-to-end testing because the ltc294x_configure_sync function is hanging for me.

**Comment by adkinsjd** [comment]
Okay it seems to be working now with the ltc294x fix. Still have not tested fm25cl.

**Comment by adkinsjd** [comment]
FM25CL tested and working.

**Pull request merged**
